# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.0

      - name: Navigate to Server Directory
        run: cd server

      - name: Install dependencies
        run: dart pub get
        working-directory: ./server

      - name: Run tests
        run: dart test
        working-directory: ./server

      - name: Create Build Directory if it doesnt exsist
        run: mkdir -p build
        working-directory: ./server

      - name: Build
        run: dart compile exe bin/server.dart -o build/server
        working-directory: ./server
